In [5]:
import pandas as pd
import numpy as np

In [8]:
df = pd.DataFrame({'age':[ 3,  29], 'height': [94, 170],'weight': [31, 115]})

In [9]:
df.values

array([[  3,  94,  31],
       [ 29, 170, 115]])

In [12]:
X=np.hstack(df.values)

In [13]:
X

array([  3,  94,  31,  29, 170, 115])

In [16]:
X1=np.hstack((df['age'].values, df['height'].values, df['weight'].values))

In [17]:
X1

array([  3,  29,  94, 170,  31, 115])

In [18]:
#After feature engineering step you stack the column values horizontally using hstack
X2=np.hstack((df['age'], df['height'], df['weight']))

In [19]:
X2

array([  3,  29,  94, 170,  31, 115])