In [148]:
#the goal is to predict bad_loan
import pandas as pd
df=pd.read_csv('/Users/username/Desktop/lending_club_loan.csv')
df.head()

loan_amnt       term  int_rate  emp_length home_ownership  annual_inc  \
0       5000  36 months     10.65        10.0           RENT     24000.0   
1       2500  60 months     15.27         0.0           RENT     30000.0   
2       2400  36 months     15.96        10.0           RENT     12252.0   
3      10000  36 months     13.49        10.0           RENT     49200.0   
4       5000  36 months      7.90         3.0           RENT     36000.0   

          purpose addr_state    dti  delinq_2yrs  revol_util  total_acc  \
0     credit_card         AZ  27.65          0.0        83.7        9.0   
1             car         GA   1.00          0.0         9.4        4.0   
2  small_business         IL   8.72          0.0        98.5       10.0   
3           other         CA  20.00          0.0        21.0       37.0   
4         wedding         AZ  11.20          0.0        28.3       12.0   

   bad_loan  longest_credit_length verification_status  
0         0                   26.0            verified  
1         1                   12.0            verified  
2         0                   10.0        not verified  
3         0                   15.0            verified  
4         0                    7.0            verified

In [149]:
df['delinq_2yrs'].unique()

array([ 0.,  2.,  3.,  1.,  4.,  6.,  5.,  8.,  7.,  9., 11., nan, 13.,
       10., 15., 18., 12., 29., 14., 16.])

In [150]:
df['term'].unique()

array(['36 months', '60 months'], dtype=object)

In [151]:
#first convert months into years. so 36 months become 3 (years) and 60 months become 5 (years)
df['term'] = [3 if x == '36 months' else 5 for x in df['term']]

In [152]:
df.head()

loan_amnt  term  int_rate  emp_length home_ownership  annual_inc  \
0       5000     3     10.65        10.0           RENT     24000.0   
1       2500     5     15.27         0.0           RENT     30000.0   
2       2400     3     15.96        10.0           RENT     12252.0   
3      10000     3     13.49        10.0           RENT     49200.0   
4       5000     3      7.90         3.0           RENT     36000.0   

          purpose addr_state    dti  delinq_2yrs  revol_util  total_acc  \
0     credit_card         AZ  27.65          0.0        83.7        9.0   
1             car         GA   1.00          0.0         9.4        4.0   
2  small_business         IL   8.72          0.0        98.5       10.0   
3           other         CA  20.00          0.0        21.0       37.0   
4         wedding         AZ  11.20          0.0        28.3       12.0   

   bad_loan  longest_credit_length verification_status  
0         0                   26.0            verified  
1         1                   12.0            verified  
2         0                   10.0        not verified  
3         0                   15.0            verified  
4         0                    7.0            verified

In [153]:
len(df)

163987

In [154]:
16398*10

163980

In [ ]:
dti: debt to income ratio (<=40)





In [155]:
df['total_acc'].unique()

array([  9.,   4.,  10.,  37.,  12.,  13.,   3.,  23.,  34.,  11.,  29.,
        28.,  42.,  14.,  38.,  21.,  17.,   7.,  31.,  22.,  44.,  26.,
        16.,   6.,  18.,  27.,  25.,  40.,  35.,  24.,   8.,  20.,  15.,
        19.,  36.,  51.,  32.,  30.,  33.,  46.,   5.,  61.,  56.,  50.,
        41.,  79.,  43.,  47.,  53.,  45.,  60.,  55.,  39.,  52.,  58.,
        54.,  57.,  49.,  63.,  48.,  59.,  62.,  77.,  87.,  75.,  72.,
        64.,  67.,  78.,  76.,  74.,  66.,  81.,  90.,  80.,  71.,  69.,
        73.,  70.,  68.,  65.,   2.,   1.,  nan,  88.,  82.,  91.,  99.,
        92.,  85.,  93.,  83.,  84., 118.,  94., 102.,  95.])

In [156]:
#let's check whether the column term is of integer type
df['term'].dtype
    

dtype('int64')

In [157]:
#next step is to convert the columns with text values into numeric type
#Does None mean the customers do not own any home?
df['home_ownership'].unique()

array(['RENT', 'OWN', 'MORTGAGE', 'OTHER', 'NONE', 'ANY'], dtype=object)

In [158]:
#check with Ram whether they collect any evidence from customers to prove the purpose
df['purpose'].unique()

array(['credit_card', 'car', 'small_business', 'other', 'wedding',
       'debt_consolidation', 'home_improvement', 'major_purchase',
       'medical', 'moving', 'vacation', 'house', 'renewable_energy',
       'educational'], dtype=object)

In [159]:
df['verification_status'].unique()

array(['verified', 'not verified'], dtype=object)

In [160]:
len(df['addr_state'].unique())

50

In [161]:
#first try to convert the text values into numeric ones using pd.get_dummies
df = pd.concat([df.drop('home_ownership', axis=1), pd.get_dummies(df['home_ownership'], drop_first=True)], axis=1)

In [162]:
df.head()

loan_amnt  term  int_rate  emp_length  annual_inc         purpose  \
0       5000     3     10.65        10.0     24000.0     credit_card   
1       2500     5     15.27         0.0     30000.0             car   
2       2400     3     15.96        10.0     12252.0  small_business   
3      10000     3     13.49        10.0     49200.0           other   
4       5000     3      7.90         3.0     36000.0         wedding   

  addr_state    dti  delinq_2yrs  revol_util  total_acc  bad_loan  \
0         AZ  27.65          0.0        83.7        9.0         0   
1         GA   1.00          0.0         9.4        4.0         1   
2         IL   8.72          0.0        98.5       10.0         0   
3         CA  20.00          0.0        21.0       37.0         0   
4         AZ  11.20          0.0        28.3       12.0         0   

   longest_credit_length verification_status  MORTGAGE  NONE  OTHER  OWN  RENT  
0                   26.0            verified         0     0      0    0     1  
1                   12.0            verified         0     0      0    0     1  
2                   10.0        not verified         0     0      0    0     1  
3                   15.0            verified         0     0      0    0     1  
4                    7.0            verified         0     0      0    0     1

In [163]:
#To convert the column: purpose the similar way as above 
df = pd.concat([df.drop('purpose', axis=1), pd.get_dummies(df['purpose'], drop_first=True)], axis=1)

In [164]:
#It is time to convert the verification_status column values. To make it bit more punitive efficient have assigned -1 to 'not verified' value in the column: verification_status

df['verification_status'] = [1 if x == 'verified' else -1 for x in df['verification_status']]


In [165]:
#The column: addr_state has 50 states as values so there will be a lot of 1s and 0s. But for now going to stick with pd.get_dummies
df = pd.concat([df.drop('addr_state', axis=1), pd.get_dummies(df['addr_state'], drop_first=True)], axis=1)

In [166]:
df = df.fillna(0)

In [167]:
#Assign y the values to be predicted
y=df['bad_loan'].values

In [168]:
y

array([0, 1, 0, ..., 0, 0, 0])

In [169]:
#Drop y from the rest of the dataframe and assign the result to X
df=df.drop('bad_loan', axis=1)

In [170]:
df.columns = df.iloc[0]


In [171]:
X=df.values

In [173]:
X

array([[5.0000e+03, 3.0000e+00, 1.0650e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.5000e+03, 5.0000e+00, 1.5270e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.4000e+03, 3.0000e+00, 1.5960e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [1.2825e+04, 3.0000e+00, 1.7140e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.7650e+04, 5.0000e+00, 2.1990e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.7000e+04, 5.0000e+00, 1.5990e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [22]:
#Have to know more about the fields in order to meaningfully assign values to null values in the dataset. For now keeping
#it simple and replacing all the null values in the dataset with 0


In [34]:
X.isnull().any()

loan_amnt                False
term                     False
int_rate                 False
emp_length               False
annual_inc               False
dti                      False
delinq_2yrs              False
revol_util               False
total_acc                False
longest_credit_length    False
verification_status      False
MORTGAGE                 False
NONE                     False
OTHER                    False
OWN                      False
RENT                     False
credit_card              False
debt_consolidation       False
educational              False
home_improvement         False
house                    False
major_purchase           False
medical                  False
moving                   False
other                    False
renewable_energy         False
small_business           False
vacation                 False
wedding                  False
AL                       False
                         ...  
MD                       False
ME      

In [174]:
#While doing this step be cautious, because if you refresh it again and again then you risk exposing all parts of the dataset to the model
#So there is literally no separate or untouched test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [37]:
#Fitting Logistic Regression model to the data

In [175]:
#Getting training and validation sets from X_train and y_train. The ideais to keep the X_test and y_test aside
X_train1, X_valid1, y_train1, y_valid1=train_test_split(X_train, y_train, random_state=42)

In [176]:
len(X_train1)

92242

In [177]:
len(y_train1)

92242

In [178]:
type(np.array(y_train1))

numpy.ndarray

In [69]:
#The goal of cross validation here is to understand how well the model performs on unseen data by calculating the cross_validation error

# from sklearn.linear_model import LogisticRegression
# clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr').fit(X_train1, y_train1)


In [90]:
# #This is right but I have to add a loop to iterate the samples
# from sklearn.utils import resample
# X_resample, y_resample = resample(X_train1, y_train1, n_samples=50, random_state=0)

In [179]:
# y_resample.values

In [193]:
def bootstrap_samples(x, y):
    from sklearn.utils import resample
    from sklearn.linear_model import LogisticRegression
    import numpy as np
    predictions=[]
    observed_y=[]
    n_iterations=10
    n_samples=9224
    count_estimate_variance=0
    for i in range(n_iterations):
        print(x.shape)
        X_resample= resample(x, n_samples, random_state=0)
        print(X_resample)
        test_oob_x, =np.array([X_test for X_test in x if X_test not in X_resample])
        test_oob_y = np.array([y_test for y_test in y if y_test not in y_resample])
        clf = LogisticRegression(random_state=0, solver='lbfgs',multi_class='ovr')
        clf.fit(X_resample, y_resample)
        predictions.append(clf.predict(test_oob_x))
        observed_y.append(test_oob_y)
    avg_predictions=sum(predictions)/len(predictions)
    avg_observed_y=sum(observed_y)/len(observed_y)
    prediction_bias=avg_predictions-avg_observed_y
    for j in predictions:
        calc_pred_avg=(j-avg_predictions)**2
        count_estimate_variance+=calc_pred_avg
    estimate_variance=count_estimate_variance/(n_samples-1)
    return prediction_bias, estimate_variance


In [194]:
bootstrap_samples(X_train1, y_train1)

(92242, 78)


TypeError: Expected sequence or array-like, got <class 'int'>

In [70]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [103]:
import numpy as np
X = np.array([[1., 0.], [2., 1.], [0., 0.]])
y = np.array([0, 1, 2])

from sklearn.utils import resample
X, y = resample(X, y, random_state=0)
X, y

(array([[1., 0.],
        [2., 1.],
        [1., 0.]]), array([0, 1, 0]))