In [38]:
#Looks like one hot encoder accepts input in 2D array format

# OneHotEncoder cannot process string values directly. If your nominal features are strings, then you need to first map 
# them into integers.

# pandas.get_dummies is kind of the opposite. By default, it only converts string columns into one-hot representation, 
# unless columns are specified.


from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
# X = [['Male', 1], ['Female', 3], ['Female', 2]]
# enc.fit(X)
X=[["paris", 1], ["paris", 1], ["tokyo",2], ["amsterdam",3]]
enc.fit(X)

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='ignore',
       n_values=None, sparse=True)

In [39]:
enc.transform([["tokyo",2], ["tokyo",2], ["paris",1], ["germany",4], [None, 0]]).toarray()

array([[0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [35]:
#One Hot Encoder has a way to encode None, but the problem is that it could get same encoding as that of another variable
#This way of encoding might send misleading info
enc.transform([["tokyo",2], ["tokyo",2], ["paris",1], ["germany",4], [None, 5]]).toarray()

array([[0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train = ["paris", "paris", "tokyo", "amsterdam"]
test = ["tokyo", "tokyo", "paris"]
le1=le.fit(train).transform(test)
le1

array([2, 2, 1])

In [12]:
import pandas as pd
pd.get_dummies(le1)

1  2
0  0  1
1  0  1
2  1  0

In [13]:
pd.get_dummies(train)

amsterdam  paris  tokyo
0          0      1      0
1          0      1      0
2          0      0      1
3          1      0      0

In [26]:
#If None is converted into string format then that will be considered as a separate variable and will be treated like rest
#of the variables in a column for example. We are completely eliminating None as 0 instead trying to pass some info 
#by encoding all the none values in the same format

lk=['great', 'average', 'poor', 'None']

gor=le.fit(lk).transform(lk)

In [27]:
pd.get_dummies(gor)

0  1  2  3
0  0  0  1  0
1  0  1  0  0
2  0  0  0  1
3  1  0  0  0

In [25]:
#pd.get_dummies convert None into zeros
pd.get_dummies(['great', 'average', 'poor', None])

average  great  poor
0        0      1     0
1        1      0     0
2        0      0     1
3        0      0     0