In [1]:
import numpy as np

In [2]:
dWax = np.random.randn(5,3)*10

# dWya = np.random.randn(2,5)*10
# db = np.random.randn(5,1)*10
# dby = np.random.randn(2,1)*10


In [3]:
dWax

array([[  5.72747626,  14.10880603,  -4.07655752],
       [-12.7268726 ,   0.50812482, -11.93396853],
       [ -2.21932677,   5.86116034,  25.88585026],
       [ 19.35574264,  -9.13906209,  15.97523642],
       [  7.44025786,  16.29066991,  14.44426297]])

In [4]:
dWaa = np.random.randn(5,5)*10

In [5]:
dWaa

array([[  3.25104955, -16.59823503,  -6.37918591,   0.0492513 ,
        -18.92751789],
       [ 10.89031348, -28.99935625,  10.85562958,  10.44545895,
          0.78994174],
       [ -9.72276176,   3.24765089,   3.67571324,   5.19428449,
          8.56127634],
       [ -9.39031003,  -7.27985537,  -6.86792215,   0.24831099,
         -2.31927692],
       [-11.43516556,  -2.84561694,   0.53372077,  -7.22127036,
         -3.63359028]])

In [7]:
for i in [dWax, dWaa]:
    i=np.clip(i, -10, 10)
    print(i)
    

[[  5.72747626  10.          -4.07655752]
 [-10.           0.50812482 -10.        ]
 [ -2.21932677   5.86116034  10.        ]
 [ 10.          -9.13906209  10.        ]
 [  7.44025786  10.          10.        ]]
[[  3.25104955 -10.          -6.37918591   0.0492513  -10.        ]
 [ 10.         -10.          10.          10.           0.78994174]
 [ -9.72276176   3.24765089   3.67571324   5.19428449   8.56127634]
 [ -9.39031003  -7.27985537  -6.86792215   0.24831099  -2.31927692]
 [-10.          -2.84561694   0.53372077  -7.22127036  -3.63359028]]


In [ ]:
You will need to use the argument "out = ...".
Using the "out" parameter allows you to update a variable "in-place".
If you dont use "out" argument, the clipped variable is stored in the variable "gradient" but does not update the 
gradient variables dWax, dWaa, dWya, db, dby.

np.clip(gradient, -maxValue, maxValue, out=gradient)

In [ ]:
Out - parameter - numpy

https://stackoverflow.com/questions/33398096/numpy-passing-input-array-as-out-argument-to-ufunc


The out parameter of a numpy function is the array where the result is written. The main advantage of using out is avoiding the allocation of new memory where it is not necessary.

Is it safe to use write the output of a function on the same array passed as input? There is no general answer, it depends on what the function is doing.


