In [19]:
from sklearn.externals import joblib
df=joblib.load('churn_train_dataset')

In [20]:
df.head()

avg_dist  avg_rating_by_driver  avg_rating_of_driver  avg_surge  \
0      6.94                   5.0                   5.0       1.00   
1      8.06                   5.0                   5.0       1.00   
2     21.50                   4.0                   5.0       1.00   
3      9.46                   5.0                   5.0       2.75   
4     13.77                   5.0                   5.0       1.00   

   last_trip_date  signup_date  surge_pct  trips_in_first_30_days  \
0             122           11        0.0                       0   
1              25           24        0.0                       2   
2             140            1        0.0                       1   
3               9            8      100.0                       1   
4             132           30        0.0                       0   

   luxury_car_user  weekday_pct  churn  city_Astapor  city_King's Landing  \
0                1        100.0      1             1                    0   
1                1          0.0      1             1                    0   
2                1        100.0      1             0                    0   
3                1        100.0      1             0                    0   
4                1        100.0      1             0                    0   

   city_Winterfell  phone_Android  phone_iPhone  
0                0              1             0  
1                0              1             0  
2                1              0             1  
3                1              1             0  
4                1              0             1

In [ ]:
#check this link for which algorithms we actually have to scale the data in order to classify it?
#https://stats.stackexchange.com/questions/244507/what-algorithms-need-feature-scaling-beside-from-svm
    
    

In [2]:
y=df['churn'].values
df.drop('churn', inplace=True, axis=1)
X=df.values

In [3]:
#Under-sampling: Tomek links
from imblearn.under_sampling import TomekLinks

tl = TomekLinks(ratio='majority')
X_tl, y_tl= tl.fit_sample(X, y)

In [4]:
X_tl

array([[ 6.94,  5.  ,  5.  , ...,  0.  ,  1.  ,  0.  ],
       [ 8.06,  5.  ,  5.  , ...,  0.  ,  1.  ,  0.  ],
       [21.5 ,  4.  ,  5.  , ...,  1.  ,  0.  ,  1.  ],
       ...,
       [ 3.04,  5.  ,  5.  , ...,  1.  ,  1.  ,  0.  ],
       [ 3.49,  4.3 ,  3.3 , ...,  0.  ,  0.  ,  1.  ],
       [ 4.25,  4.7 ,  5.  , ...,  0.  ,  0.  ,  1.  ]])

In [7]:
len(y_tl)

39910

In [5]:
y_tl

array([1, 1, 1, ..., 0, 1, 0])

In [4]:
def plot_2d_space(X, y, label='Classes'):   
    colors = ['#1F77B4', '#FF7F0E']
    markers = ['o', 's']
    for l, c, m in zip(np.unique(y), colors, markers):
        plt.scatter(
            X[y==l, 0],
            X[y==l, 1],
            c=c, label=l, marker=m
        )
    plt.title(label)
    plt.legend(loc='upper right')
    plt.show()

In [5]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plot_2d_space(X_tl, y_tl, 'Tomek links under-sampling')#because we are removing the majority of classes



NameError: name 'plot_2d_space' is not defined

In [8]:
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(ratio={1: 150})
X_cc, y_cc = cc.fit_sample(X, y)

y_cc

#plot_2d_space(X_cc, y_cc, 'Cluster Centroids under-sampling')

array([0, 0, 0, ..., 1, 1, 1])

In [9]:
X_cc

array([[ 5.42      ,  4.7       ,  5.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 4.28      ,  5.        ,  4.        , ...,  1.        ,
         1.        ,  0.        ],
       [11.44      ,  4.6       ,  4.7       , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [17.20833333,  4.86333333,  4.76916667, ...,  0.58333333,
         0.38333333,  0.61666667],
       [ 3.71043478,  4.79275362,  4.55507246, ...,  0.4057971 ,
         0.37681159,  0.62318841],
       [ 6.84617886,  4.65772358,  4.63333333, ...,  0.45528455,
         0.3902439 ,  0.6097561 ]])

In [10]:
len(X_cc)

15182

In [11]:
len(y_cc)

15182

In [21]:
len(X_cc)

15182

In [22]:
len(y_cc[y_cc==0])

15032

In [23]:
len(y_cc[y_cc==1])

150

In [ ]:
cct = ClusterCentroids()
X_cc, y_cc = cct.fit_sample(X, y)
#plot_2d_space(X_cc, y_cc, 'Cluster Centroids under-sampling')

In [12]:
#Over-sampling: SMOTE
from imblearn.over_sampling import SMOTE

smote = SMOTE(ratio='minority')
X_sm, y_sm = smote.fit_sample(X, y)

#plot_2d_space(X_sm, y_sm, 'SMOTE over-sampling')


In [13]:
len(X_sm)

49936

In [14]:
#Over-sampling followed by under-sampling
from imblearn.combine import SMOTETomek

smt = SMOTETomek(ratio='auto')
X_smt, y_smt = smt.fit_sample(X, y)

#plot_2d_space(X_smt, y_smt, 'SMOTE + Tomek links')

In [15]:
len(X_smt)

49866