In [39]:
import xgboost
import pandas as pd
from xgboost import DMatrix,train

xgb_params ={    
    'booster' : 'gbtree',
    'eta': 0.1,
    'gamma' : 1.0 ,
    'min_child_weight' : 0.1,
    'objective' : 'rank:pairwise',
    'eval_metric' : 'merror',
    #'num_class': 3,  # 
    'max_depth' : 6,
    'num_round' : 4,
    'save_period' : 0 
}


n_group=2
n_choice=3    

#training dataset

dtrain=np.random.uniform(0,100,[n_group*n_choice,2])    
dtarget=np.array([np.random.choice([0,1,1],3,False) for i in range(n_group)]).flatten()

# dgroup=np.array([np.repeat(i,3)for i in range(n_group)]).flatten()
dgroup=np.array([n_choice for i in range(n_group)]).flatten()

xgbTrain = DMatrix(dtrain, label = dtarget)
# xgbTrain =xgbTrain.set_group(dgroup)
xgbTrain.set_group(dgroup)

#watchlist

dtrain_eval=np.random.uniform(0,100,[n_group*n_choice,2])        

xgbTrain_eval = DMatrix(dtrain_eval, label = dtarget)
#xgbTrain_eval =xgbTrain_eval .set_group(dgroup)

#test dataset

dtest=np.random.uniform(0,100,[n_group*n_choice,2])    
dtestgroup=np.array([np.repeat(i,3)for i in range(n_group)]).flatten()

# dtestgroup=np.array([n_choice for i in range(n_group)]).flatten()

xgbTest = DMatrix(dtest)
xgbTest =xgbTest.set_group(dgroup)
evallist  = [(xgbTrain_eval, 'eval')]

rankModel = xgboost.train(params=xgb_params,dtrain=xgbTrain, evals=evallist)
print(rankModel.predict( xgbTest))

XGBoostError: [18:23:08] src/metric/multiclass_metric.cu:32: Check failed: label_error >= 0 && label_error < static_cast<int32_t>(n_class): MultiClassEvaluation: label must be in [0, num_class), num_class=1 but found 1 in label
Stack trace:



In [1]:
import numpy as np
n_group=2
n_choice=3    

#training dataset

dtrain=np.random.uniform(0,100,[n_group*n_choice,2])    

In [2]:
dtrain

array([[71.6133958 , 50.03515258],
       [13.70894581, 84.81618169],
       [ 9.21887106, 24.06211061],
       [51.04989952, 65.72474127],
       [23.07336674, 30.55599078],
       [74.66508017, 71.64679532]])

array([71.6133958 , 50.03515258])

In [33]:
dtarget=np.array([np.random.choice([0,1,1],3,False) for i in range(n_group)]).flatten()

In [34]:
dtarget

array([0, 1, 1, 1, 1, 0])

In [5]:
this means that for the range(groups) in n_group, repeat the values for three times, i.e., mean to indicate there are
two groups: 0 and 1

dgroup=np.array([np.repeat(i,3)for i in range(n_group)]).flatten()
dgroup

array([0, 0, 0, 1, 1, 1])

In [10]:
from xgboost import DMatrix,train



xgbTrain = DMatrix(dtrain, label = dtarget)

In [14]:
xgbTrain

In [15]:
dtest=np.random.uniform(0,100,[n_group*n_choice,2])    


In [16]:
dtest

array([[75.2564814 , 64.36155633],
       [58.18921896, 45.65387364],
       [74.98481938, 14.09187464],
       [81.83516093,  3.81246402],
       [ 9.13155473, 11.84568721],
       [57.54215796, 88.11438514]])

In [17]:
dtestgroup=np.array([np.repeat(i,3)for i in range(n_group)]).flatten()

dtestgroup

array([0, 0, 0, 1, 1, 1])

In [20]:
dgroup=np.array([n_choice for i in range(n_group)]).flatten()

In [21]:
dgroup

array([3, 3])